<h2>User verwalten</h2>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td>ID</td>
			<td>Username</td>
			<td>Anzeigename</td>
			<td>Bearbeiten</td>
			<td>Löschen</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator AS $one): ?>
		<?php if($this->role == 'member' && $one['role'] != 'admin'): ?>
		<tr>
			<td><?php echo $one['id']; ?>
			<td><?php echo $one['username']; ?>
			<td><?php echo $one['realname']; ?>
			<td><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'edit', 'id' => $one['id']), null, true); ?>">Klick</a></td>
			<td><a class="delete" rel="User" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'delete', 'id' => $one['id']), null, true); ?>">Klick</a></td>
		</tr>
		<?php endif; ?>
		<?php if($this->role == 'admin'): ?>
		<tr>
			<td><?php echo $one['id']; ?>
			<td><?php echo $one['username']; ?>
			<td><?php echo $one['realname']; ?>
			<td><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'edit', 'id' => $one['id']), null, true); ?>">Klick</a></td>
			<td><a class="delete" rel="User" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'delete', 'id' => $one['id']), null, true); ?>">Klick</a></td>
		</tr>
		<?php endif; ?>
		<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination.phtml'); ?>