<h2>Gästebuch-Einträge verwalten</h2>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td>ID</td>
			<td>Ersteller</td>
			<td>Antwort zu</td>
			<td>erstellt</td>
			<td>Antworten</td>
			<td>Löschen</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator AS $one): ?>
		<tr>
			<td><?php echo $one['id']; ?>
			<td><?php echo $one['creator']; ?>
			<td><?php echo $one['answerTo']; ?>
			<td><?php echo $this->dateTime($one['date']); ?>
			<?php if (strlen($one['answerTo']) === 0): ?>
			<td><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'guestbook', 'action' => 'answer', 'id' => $one['id']), null, true); ?>">Klick</a></td>
			<?php else: ?>
			<td>Klick</td>
			<?php endif; ?>
			<td><a class="delete" rel="Gästebucheintrag" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'guestbook', 'action' => 'delete', 'id' => $one['id']), null, true); ?>">Klick</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination.phtml'); ?>