<h2>News-Einträge verwalten</h2>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<td>ID</td>
			<td>Titel</td>
			<td>erstellt</td>
			<td>Bearbeiten</td>
			<td>Löschen</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->paginator AS $one): ?>
		<tr>
			<td><?php echo $one['id']; ?>
			<td><?php echo $one['title']; ?>
			<td><?php echo $this->dateTime($one['date']); ?>
			<td><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'news', 'action' => 'edit', 'id' => $one['id']), null, true); ?>">Klick</a></td>
			<td><a class="delete" rel="Newseintrag" href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'news', 'action' => 'delete', 'id' => $one['id']), null, true); ?>">Klick</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Elastic', 'pagination.phtml'); ?>