<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Admin Bereich</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <link href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->baseUrl(); ?>/css/admin.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.min.js"></script>
</head>
<body>
    <div class="container-fluid">
		<div class="row-fluid">
			<div class="span12" style="text-align:center;">
				<div class="well">
					<h3>Admin Bereich</h3>
					<?php $auth = Zend_Auth::getInstance();
						echo 'Eingeloggt als: ' . $auth->getIdentity()->username; ?>
				</div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2">
				<div class="well">
				<span><b>» Main «</b></span><br />
            <a href="<?php echo $this->url(array('module'=>'admin','controller'=>'index','action'=>'index'), null, true);?>">Hauptseite</a><br /><br />
			<span><b>» Test «</b></span><br />
			<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true); ?>">verwalten</a><br />
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true); ?>">hinzufügen</a><br /><br />
			<span><b>» Test «</b></span><br />
			<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true); ?>">verwalten</a><br />
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true); ?>">hinzufügen</a><br /><br />
            <span><b>» Test «</b></span><br />
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true); ?>">verwalten</a><br />
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true); ?>">hinzufügen</a><br /><br />
            <span><b>» Test «</b></span><br />
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true);?>">verwalten</a><br />
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), null, true);?>">hinzufügen</a><br /><br />
			</div>
			</div>
			<div class="span10">
				<div class="well">
				<?php echo $this -> layout () -> content; ?>
				</div>
			</div>
		</div>
    </div>
</body>
</html>