<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Tierschutzverein Eilenburg e.V.</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
	<link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.min.js"></script>
</head>
<body>
	<div id="wrapper">
		<div id="head"><h5>Eventuell aktuelles Datum / Zeit / Willkommenstext</h5></div>
		<div id="navlist"><h1>Navigation</h1></div>
		<div id="headerimagefield"><h3>Titelbild / eventuell &Uuml;berblendeffekte per jQuery</h3></div>
		<div id="main">
			<div id="leftcontent">
					<?php echo $this->layout()->content; ?>
			</div>
			<div id="rightcontent">
				<?php echo $this->render('about/openinghours.phtml', NULL);?>
				<div id="social_networks">
		            <a href="http://www.facebook.com/pages/Tierheim-Eilenburg/135294409942475" target="_blank"><img src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl().'/img/facebook.png' ?>" /></a>
	            	<br />
	            	<hr />
	            </div>
			</div>
		</div>
	</div>
<div style="clear: both;"></div>
</body>
</html>