<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Tierschutzverein Eilenburg e.V.</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
	<link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.min.js"></script>
</head>
<body>
	<div id="wrapper">
		<div id="head"><h5>Eventuell aktuelles Datum / Zeit / Willkommenstext</h5></div>
		<div id="navlist"><h1>Navigation</h1></div>
		<div id="headerborder">
			<div id="headerimagefield">
				<div id="slideshow">
				   <div>
					 <img src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl() . '/img/tierheim.jpg'?>" />				   
				   </div>
				   <div>
				     <img src="http://farm6.static.flickr.com/5224/5658667829_2bb7d42a9c_m.jpg" />
				   </div>
				   <div>
				     <img src="http://farm6.static.flickr.com/5230/5638093881_a791e4f819_m.jpg" />
				   </div>
				   <div>
				     Text geht auch. Stark :D
				   </div>
			   </div>
			</div>
		</div>
		<div id="headerContentSeparation"></div>
		<div id="main">
			<div id="leftcontent">
					<?php echo $this->layout()->content; ?>
			</div>
			<div id="rightcontent">
				<?php echo $this->render('about/openinghours.phtml', NULL);?>
				<div id="social_networks">
		            <a href="http://www.facebook.com/pages/Tierheim-Eilenburg/135294409942475" target="_blank"><img src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl().'/img/facebook.png' ?>" /></a>
	            	<br />
	            	<hr />
	            </div>
	            
	            <?php echo $this->render('about/phone.phtml', NULL);?>
			</div>
		</div>
	</div>
<div style="clear: both;"></div>
<script type="text/javascript">
$("#slideshow > div:gt(0)").hide();

setInterval(function() { 
  $('#slideshow > div:first')
    .fadeOut(1000)
    .next()
    .fadeIn(1000)
    .end()
    .appendTo('#slideshow');
},  3000);</script>

</body>
</html>