<!doctype html>
<html lang="en">
<head>
<?php $this->headTitle()->setPostFix(' - Tierschutzverein Eilenburg e.V.'); ?>
<?php echo $this->headTitle(); ?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content=""/>
<meta name="keywords" content="tier, tierfutter, bedarf, hund, katze, kleintiere, futter" />
<meta name="author" content=""/>
<!-- mobile viewport optimisation -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php $baseUrl = $this->baseUrl(); ?>
<!-- stylesheets -->
<?php echo $this->minifyHeadLink()
                ->prependStylesheet('/css/bootstrap.css')
				->appendStylesheet('/css/bootstrap.layout.css');
?>
<?php echo $this->minifyHeadScript()
                ->prependFile('/js/jquery.min.js')
				->appendFile('/js/bootstrap.js')
				->appendFile('/js/jquery.tooltip.js');
?>
</head>
<body>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<div class="mycontainer">
		<div class="row-fluid">
			<div class="span12" id="header">
				<div style="float:left;"><a href="/" id="headlogo">Bild</a></div>
				<div style="float:left;margin-left:100px;width:650px;">
					<div class="btn-group" style="margin-left:100px;">
						<a class="btn btn-success" href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Start</a>
						<a class="btn btn-warning" href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">index</a>
						<a class="btn btn-info" href="">index</a>
						<a class="btn btn-danger" href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">index</a>
						<a class="btn btn-primary" href="">index</a>
					</div>
					
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2" id="navigation">
				<div class="well" style="padding: 8px 0;">
				<ul class="nav nav-list">
					<li class="nav-header">Test</li>
					<li><a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' =>'index', 'default', true); ?>"><i class="icon-chevron-right"></i>index</a></li>
					<li class="divider"></li>
					<li class="nav-header">Wichtiges</li>
					<li><a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="icon-chevron-right"></i> index</a></li>
					<li><a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>"><i class="icon-chevron-right"></i> index</a></li>
				</ul>
				</div>
			</div>
			<div class="span10" id="content">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12" id="footer">
				| <a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Startseite</a> | 
				<a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Startseite</a> | 
				<a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Startseite</a> | 
				<a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Startseite</a> | 
				<a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Startseite</a> | 
				<a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'impress', true); ?>">Startseite</a> | 
				<a href="<?php echo $this->url(array('module' => 'system', 'controller' => 'index', 'action' => 'index'), 'default', true); ?>">Startseite</a> |
			<br /><br/>
			<div class="fb-like" data-send="true" data-layout="button_count" data-width="250" data-show-faces="false"></div>
			<br /><br/>
			Copyright &copy; 2012 Tierschutzverein Eilenburg e.V. - Powered by Twitter Bootstrap
			</div>
		</div>
	</div>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</body>
</html>
